# Generated by Django 6.0.6 on 2026-06-24 17:55

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_empresa_table_alter_historicalempresa_table_and_more'),
        ('empreendimentos', '0011_historicalunidade_gars_tab_vendas_and_more'),
        ('pessoas', '0002_alter_historicalpessoa_table_and_more'),
        ('vendas', '0005_tabelaserie_percentual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor hexadecimal, ex: #3B82F6', max_length=7, verbose_name='Cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_inicial', models.BooleanField(default=False, help_text='Nova negociação entra nesta etapa', verbose_name='Etapa inicial')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_workflow', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Etapa do Workflow',
                'verbose_name_plural': 'Etapas do Workflow',
                'db_table': 'inc_etapa_workflow',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNegociacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Número')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('vendida', 'Vendida'), ('distrato', 'Distrato')], default='ativa', max_length=10, verbose_name='Status')),
                ('data_abertura', models.DateField(blank=True, editable=False, verbose_name='Data de abertura')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deletado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.empreendimento')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('etapa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='negociacoes.etapaworkflow')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tabela_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.tabelavendasitem', verbose_name='Item da tabela de vendas')),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.unidade')),
            ],
            options={
                'verbose_name': 'historical Negociação',
                'verbose_name_plural': 'historical Negociações',
                'db_table': 'inc_historical_negociacao',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('vendida', 'Vendida'), ('distrato', 'Distrato')], default='ativa', max_length=10, verbose_name='Status')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de abertura')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negociacoes', to='empreendimentos.empreendimento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacoes', to='core.empresa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negociacoes', to='negociacoes.etapaworkflow')),
                ('tabela_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negociacoes', to='vendas.tabelavendasitem', verbose_name='Item da tabela de vendas')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negociacoes', to='empreendimentos.unidade')),
            ],
            options={
                'verbose_name': 'Negociação',
                'verbose_name_plural': 'Negociações',
                'db_table': 'inc_negociacao',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('etapa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='negociacoes.etapaworkflow')),
                ('etapa_nova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='negociacoes.etapaworkflow')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('negociacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='negociacoes.negociacao')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Histórico de Etapas',
                'db_table': 'inc_historico_negociacao',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ParteNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proponente', 'Proponente'), ('conjuge_proponente', 'Cônjuge do Proponente'), ('segundo_proponente', 'Segundo Proponente'), ('conjuge_segundo', 'Cônjuge do 2º Proponente'), ('interveniente', 'Interveniente'), ('corretor', 'Corretor'), ('imobiliaria', 'Imobiliária'), ('imobiliaria_parceira', 'Imobiliária Parceira')], max_length=25, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('negociacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='negociacoes.negociacao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'Parte da Negociação',
                'verbose_name_plural': 'Partes da Negociação',
                'db_table': 'inc_parte_negociacao',
                'ordering': ['ordem', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='SerieNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ato', 'Ato'), ('parcelas_mensais', 'Parcelas Mensais'), ('reforcos', 'Reforços'), ('chaves', 'Chaves'), ('financiamento', 'Financiamento'), ('dacao', 'Dação'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Qtd. parcelas')),
                ('valor_por_parcela', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor por parcela')),
                ('data_primeiro_vencimento', models.DateField(blank=True, null=True, verbose_name='Data 1º vencimento')),
                ('periodicidade', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='', max_length=15, verbose_name='Periodicidade')),
                ('negociacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='negociacoes.negociacao')),
                ('serie_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.tabelaserie', verbose_name='Série de referência (tabela)')),
            ],
            options={
                'verbose_name': 'Série da Proposta',
                'verbose_name_plural': 'Séries da Proposta',
                'db_table': 'inc_serie_negociacao',
                'ordering': ['tipo', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TransicaoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_entrada', to='negociacoes.etapaworkflow')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_saida', to='negociacoes.etapaworkflow')),
            ],
            options={
                'verbose_name': 'Transição do Workflow',
                'verbose_name_plural': 'Transições do Workflow',
                'db_table': 'inc_transicao_workflow',
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
