# Generated by Django 6.0.6 on 2026-06-25 13:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnegociacao',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='negociacao',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desconto (%)'),
        ),
    ]
