# Generated by Django 6.0.6 on 2026-06-25 15:59

import apps.negociacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacoes', '0003_negociacao_unidade_multipla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnegociacao',
            name='data_abertura',
            field=models.DateField(default=apps.negociacoes.models._date_hoje, verbose_name='Data da proposta'),
        ),
        migrations.AlterField(
            model_name='negociacao',
            name='data_abertura',
            field=models.DateField(default=apps.negociacoes.models._date_hoje, verbose_name='Data da proposta'),
        ),
    ]
