# Generated by Django 6.0.6 on 2026-06-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacoes', '0004_data_abertura_editavel'),
        ('vendas', '0005_tabelaserie_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnegociacao',
            name='tabela',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.tabelavendas', verbose_name='Tabela de vendas'),
        ),
        migrations.AddField(
            model_name='negociacao',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negociacoes', to='vendas.tabelavendas', verbose_name='Tabela de vendas'),
        ),
    ]
