# Generated by Django 6.0.6 on 2026-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
        migrations.AddField(
            model_name='bloco',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='historicalbloco',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
