# Generated by Django 6.0.6 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0002_bloco_add_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='adicionais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adicionais'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='adicionais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adicionais'),
        ),
    ]
