# Generated by Django 6.0.6 on 2026-06-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0003_unidade_add_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='nome_hb',
            field=models.CharField(blank=True, max_length=20, verbose_name='Designação HB'),
        ),
        migrations.AddField(
            model_name='historicalunidade',
            name='unidade_principal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.unidade', verbose_name='Unidade principal'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='nome_hb',
            field=models.CharField(blank=True, max_length=20, verbose_name='Designação HB'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='unidade_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complementares', to='empreendimentos.unidade', verbose_name='Unidade principal'),
        ),
    ]
