# Generated by Django 6.0.6 on 2026-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0004_unidade_vinculo_principal_e_nome_hb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounidade',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Tipo de unidade', 'verbose_name_plural': 'Tipos de unidade'},
        ),
        migrations.AddField(
            model_name='historicaltipounidade',
            name='categoria',
            field=models.CharField(choices=[('principal', 'Principal'), ('complementar', 'Complementar')], default='principal', max_length=12, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='categoria',
            field=models.CharField(choices=[('principal', 'Principal'), ('complementar', 'Complementar')], default='principal', max_length=12, verbose_name='Categoria'),
        ),
    ]
