# Generated by Django 6.0.6 on 2026-06-13 21:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0005_tipounidade_add_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalunidade',
            name='nome_hb',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='nome_hb',
        ),
        migrations.CreateModel(
            name='HistoricalDesignacaoUnidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('garagem_carro', 'Garagem carro'), ('garagem_moto', 'Garagem moto'), ('hobby_box', 'Hobby box')], max_length=15, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'historical Designação',
                'verbose_name_plural': 'historical Designações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DesignacaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('garagem_carro', 'Garagem carro'), ('garagem_moto', 'Garagem moto'), ('hobby_box', 'Hobby box')], max_length=15, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designacoes', to='empreendimentos.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Designação',
                'verbose_name_plural': 'Designações',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('unidade', 'nome')},
            },
        ),
    ]
