# Generated by Django 6.0.6 on 2026-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0006_remove_nome_hb_add_designacaounidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('mesma_matricula', 'Mesma matrícula'), ('matricula_propria', 'Matrícula própria')], max_length=17, verbose_name='Tipo de vínculo'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('mesma_matricula', 'Mesma matrícula'), ('matricula_propria', 'Matrícula própria')], max_length=17, verbose_name='Tipo de vínculo'),
        ),
    ]
