# Generated by Django 6.0.6 on 2026-06-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0007_tipo_vinculo_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome de exibição'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome de exibição'),
        ),
    ]
