# Generated by Django 6.0.6 on 2026-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0008_nome_exibicao_unidade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloco',
            table='inc_bloco',
        ),
        migrations.AlterModelTable(
            name='designacaounidade',
            table='inc_designacao_unidade',
        ),
        migrations.AlterModelTable(
            name='empreendimento',
            table='inc_empreendimento',
        ),
        migrations.AlterModelTable(
            name='historicalbloco',
            table='inc_historical_bloco',
        ),
        migrations.AlterModelTable(
            name='historicaldesignacaounidade',
            table='inc_historical_designacao_unidade',
        ),
        migrations.AlterModelTable(
            name='historicalempreendimento',
            table='inc_historical_empreendimento',
        ),
        migrations.AlterModelTable(
            name='historicalstatusunidade',
            table='inc_historical_status_unidade',
        ),
        migrations.AlterModelTable(
            name='historicaltipounidade',
            table='inc_historical_tipo_unidade',
        ),
        migrations.AlterModelTable(
            name='historicalunidade',
            table='inc_historical_unidade',
        ),
        migrations.AlterModelTable(
            name='statusunidade',
            table='inc_status_unidade',
        ),
        migrations.AlterModelTable(
            name='tipounidade',
            table='inc_tipo_unidade',
        ),
        migrations.AlterModelTable(
            name='unidade',
            table='inc_unidade',
        ),
    ]
