# Generated by Django 6.0.6 on 2026-06-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0009_alter_bloco_table_alter_designacaounidade_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoFixada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empreendimentos.statusunidade', verbose_name='Status fixado')),
                ('unidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situacao_fixada', to='empreendimentos.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Situação Fixada',
                'verbose_name_plural': 'Situações Fixadas',
                'db_table': 'inc_situacao_fixada',
            },
        ),
    ]
