# Generated by Django 6.0.6 on 2026-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0010_situacaofixada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='gars_tab_vendas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Garagens (tabela de vendas)'),
        ),
        migrations.AddField(
            model_name='historicalunidade',
            name='hb_tab_vendas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hobby Box (tabela de vendas)'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='gars_tab_vendas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Garagens (tabela de vendas)'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='hb_tab_vendas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hobby Box (tabela de vendas)'),
        ),
    ]
