# Generated by Django 6.0.6 on 2026-06-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0011_historicalunidade_gars_tab_vendas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatusunidade',
            name='cor',
            field=models.CharField(default='#9ca3af', help_text='Cor hexadecimal, ex: #22c55e', max_length=7, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='statusunidade',
            name='cor',
            field=models.CharField(default='#9ca3af', help_text='Cor hexadecimal, ex: #22c55e', max_length=7, verbose_name='Cor'),
        ),
    ]
