# Generated by Django 6.0.6 on 2026-06-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0012_historicalstatusunidade_cor_statusunidade_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='coluna',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número da coluna no espelho de unidades', null=True, verbose_name='Coluna (espelho)'),
        ),
        migrations.AddField(
            model_name='historicalunidade',
            name='linha',
            field=models.CharField(blank=True, help_text='Ex: T, SS, 1, 2, 3 — define a linha no espelho de unidades', max_length=10, verbose_name='Linha (espelho)'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='coluna',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número da coluna no espelho de unidades', null=True, verbose_name='Coluna (espelho)'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='linha',
            field=models.CharField(blank=True, help_text='Ex: T, SS, 1, 2, 3 — define a linha no espelho de unidades', max_length=10, verbose_name='Linha (espelho)'),
        ),
    ]
