# Generated by Django 6.0.6 on 2026-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0013_historicalunidade_coluna_historicalunidade_linha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidade',
            name='descricao_linha',
            field=models.CharField(blank=True, help_text='Ex: Térreo, 1º Andar, Subsolo', max_length=50, verbose_name='Descrição da linha'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='descricao_linha',
            field=models.CharField(blank=True, help_text='Ex: Térreo, 1º Andar, Subsolo', max_length=50, verbose_name='Descrição da linha'),
        ),
        migrations.AlterField(
            model_name='historicalunidade',
            name='coluna',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número da coluna no espelho', null=True, verbose_name='Coluna (espelho)'),
        ),
        migrations.AlterField(
            model_name='historicalunidade',
            name='linha',
            field=models.CharField(blank=True, help_text='Ex: T, SS, 1, 2, 3 — define a linha no espelho', max_length=10, verbose_name='Linha (espelho)'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='coluna',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número da coluna no espelho', null=True, verbose_name='Coluna (espelho)'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='linha',
            field=models.CharField(blank=True, help_text='Ex: T, SS, 1, 2, 3 — define a linha no espelho', max_length=10, verbose_name='Linha (espelho)'),
        ),
    ]
