# Generated by Django 6.0.6 on 2026-06-26 13:13

import apps.reservas.models
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empreendimentos', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cor', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_inicial', models.BooleanField(default=False, verbose_name='Etapa inicial')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_workflow', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Etapa do Workflow',
                'verbose_name_plural': 'Etapas do Workflow',
                'db_table': 'inc_etapa_workflow',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReserva',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Numero')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('vendida', 'Vendida'), ('distrato', 'Distrato')], default='ativa', max_length=10, verbose_name='Status')),
                ('data_abertura', models.DateField(default=apps.reservas.models._date_hoje, verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deletado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.empreendimento')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('etapa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservas.etapaworkflow')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tabela', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.tabelavendas', verbose_name='Tabela de vendas')),
            ],
            options={
                'verbose_name': 'historical Reserva',
                'verbose_name_plural': 'historical Reservas',
                'db_table': 'inc_historical_reserva',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Numero')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('vendida', 'Vendida'), ('distrato', 'Distrato')], default='ativa', max_length=10, verbose_name='Status')),
                ('data_abertura', models.DateField(default=apps.reservas.models._date_hoje, verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='empreendimentos.empreendimento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.empresa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.etapaworkflow')),
                ('tabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='vendas.tabelavendas', verbose_name='Tabela de vendas')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'inc_reserva',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Numero')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='ativa', max_length=10, verbose_name='Status')),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desconto (%)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'inc_proposta',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('etapa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservas.etapaworkflow')),
                ('etapa_nova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservas.etapaworkflow')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Historico de Etapa',
                'verbose_name_plural': 'Historico de Etapas',
                'db_table': 'inc_historico_reserva',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SerieProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ato', 'Ato'), ('parcelas_mensais', 'Parcelas Mensais'), ('reforcos', 'Reforcoss'), ('chaves', 'Chaves'), ('financiamento', 'Financiamento'), ('dacao', 'Dacao'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descricao')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Qtd. parcelas')),
                ('valor_por_parcela', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor por parcela')),
                ('data_primeiro_vencimento', models.DateField(blank=True, null=True, verbose_name='Data 1 vencimento')),
                ('periodicidade', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='', max_length=15, verbose_name='Periodicidade')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='reservas.proposta')),
                ('serie_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.tabelaserie')),
            ],
            options={
                'verbose_name': 'Serie da Proposta',
                'verbose_name_plural': 'Series da Proposta',
                'db_table': 'inc_serie_proposta',
                'ordering': ['tipo', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TipoParteNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.CharField(blank=True, max_length=30, verbose_name='Codigo interno')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_parte_negociacao', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Parte',
                'verbose_name_plural': 'Tipos de Parte',
                'db_table': 'inc_tipo_parte_negociacao',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ParteReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='pessoas.pessoa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='reservas.reserva')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes', to='reservas.tipopartenegociacao')),
            ],
            options={
                'verbose_name': 'Parte da Reserva',
                'verbose_name_plural': 'Partes da Reserva',
                'db_table': 'inc_parte_reserva',
                'ordering': ['ordem', 'tipo__ordem', 'tipo__nome'],
            },
        ),
        migrations.CreateModel(
            name='ReservaUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='reservas.reserva')),
                ('tabela_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendas.tabelavendasitem')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_unidades', to='empreendimentos.unidade')),
            ],
            options={
                'verbose_name': 'Unidade da Reserva',
                'verbose_name_plural': 'Unidades da Reserva',
                'db_table': 'inc_reserva_unidade',
                'ordering': ['unidade__bloco__ordem', 'unidade__ordem', 'unidade__numero'],
                'unique_together': {('reserva', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='TransicaoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_entrada', to='reservas.etapaworkflow')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_saida', to='reservas.etapaworkflow')),
            ],
            options={
                'verbose_name': 'Transicao do Workflow',
                'verbose_name_plural': 'Transicoes do Workflow',
                'db_table': 'inc_transicao_workflow',
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
