# Generated by Django 6.0.6 on 2026-06-26 13:13

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empreendimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTabelaVendas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigência início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência fim')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deletado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.empreendimento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tabela de Vendas',
                'verbose_name_plural': 'historical Tabelas de Vendas',
                'db_table': 'inc_historical_tabela_vendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TabelaVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigência início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência fim')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_vendas', to='empreendimentos.empreendimento')),
            ],
            options={
                'verbose_name': 'Tabela de Vendas',
                'verbose_name_plural': 'Tabelas de Vendas',
                'db_table': 'inc_tabela_vendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TabelaSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ato', 'Ato'), ('parcelas_mensais', 'Parcelas Mensais'), ('reforcos', 'Reforços'), ('chaves', 'Chaves'), ('financiamento', 'Financiamento')], max_length=20, verbose_name='Tipo')),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Percentual (%)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Qtd. parcelas')),
                ('data_primeiro_vencimento', models.DateField(blank=True, null=True, verbose_name='Data 1º vencimento')),
                ('periodicidade', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='', max_length=15, verbose_name='Periodicidade')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='vendas.tabelavendas')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'db_table': 'inc_tabela_serie',
                'ordering': ['tipo'],
                'unique_together': {('tabela', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='TabelaVendasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.tabelavendas')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabela_itens', to='empreendimentos.unidade')),
            ],
            options={
                'verbose_name': 'Item da Tabela',
                'verbose_name_plural': 'Itens da Tabela',
                'db_table': 'inc_tabela_vendas_item',
                'ordering': ['unidade__bloco__ordem', 'unidade__ordem', 'unidade__numero'],
                'unique_together': {('tabela', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='TabelaVendasItemValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor por parcela')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='vendas.tabelavendasitem')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='vendas.tabelaserie')),
            ],
            options={
                'verbose_name': 'Valor do Item',
                'verbose_name_plural': 'Valores dos Itens',
                'db_table': 'inc_tabela_vendas_item_valor',
                'unique_together': {('item', 'serie')},
            },
        ),
    ]
