# Generated by Django 6.0.6 on 2026-06-23 20:52

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empreendimentos', '0008_nome_exibicao_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTabelaVendas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigência início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência fim')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deletado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empreendimentos.empreendimento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tabela de Vendas',
                'verbose_name_plural': 'historical Tabelas de Vendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TabelaVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigência início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência fim')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_vendas', to='empreendimentos.empreendimento')),
            ],
            options={
                'verbose_name': 'Tabela de Vendas',
                'verbose_name_plural': 'Tabelas de Vendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TabelaVendasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ato_qtd', models.PositiveIntegerField(default=1, verbose_name='Qtd. ato')),
                ('ato_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor ato')),
                ('parcelas_mensais_qtd', models.PositiveIntegerField(default=0, verbose_name='Qtd. parcelas mensais')),
                ('parcelas_mensais_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor parcela mensal')),
                ('reforcos_qtd', models.PositiveIntegerField(default=0, verbose_name='Qtd. reforços')),
                ('reforcos_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor reforço')),
                ('chaves_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Chaves')),
                ('financiamento_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Financiamento')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.tabelavendas')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabela_itens', to='empreendimentos.unidade')),
            ],
            options={
                'verbose_name': 'Item da Tabela',
                'verbose_name_plural': 'Itens da Tabela',
                'ordering': ['unidade__bloco__ordem', 'unidade__ordem', 'unidade__numero'],
                'unique_together': {('tabela', 'unidade')},
            },
        ),
    ]
