# Generated by Django 6.0.6 on 2026-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicaltabelavendas',
            table='inc_historical_tabela_vendas',
        ),
        migrations.AlterModelTable(
            name='tabelavendas',
            table='inc_tabela_vendas',
        ),
        migrations.AlterModelTable(
            name='tabelavendasitem',
            table='inc_tabela_vendas_item',
        ),
    ]
