# Generated by Django 6.0.6 on 2026-06-24 11:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_historicaltabelavendas_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='ato_qtd',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='ato_valor',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='chaves_valor',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='financiamento_valor',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='parcelas_mensais_qtd',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='parcelas_mensais_valor',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='reforcos_qtd',
        ),
        migrations.RemoveField(
            model_name='tabelavendasitem',
            name='reforcos_valor',
        ),
        migrations.CreateModel(
            name='TabelaSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ato', 'Ato'), ('parcelas_mensais', 'Parcelas Mensais'), ('reforcos', 'Reforços'), ('chaves', 'Chaves'), ('financiamento', 'Financiamento')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Qtd. parcelas')),
                ('data_primeiro_vencimento', models.DateField(blank=True, null=True, verbose_name='Data 1º vencimento')),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=15, verbose_name='Periodicidade')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='vendas.tabelavendas')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'db_table': 'inc_tabela_serie',
                'ordering': ['tipo'],
                'unique_together': {('tabela', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='TabelaVendasItemValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor por parcela')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='vendas.tabelavendasitem')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='vendas.tabelaserie')),
            ],
            options={
                'verbose_name': 'Valor do Item',
                'verbose_name_plural': 'Valores dos Itens',
                'db_table': 'inc_tabela_vendas_item_valor',
                'unique_together': {('item', 'serie')},
            },
        ),
    ]
