# Generated by Django 6.0.6 on 2026-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_tabelavendasitem_ato_qtd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelaserie',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='', max_length=15, verbose_name='Periodicidade'),
        ),
    ]
