# Generated by Django 6.0.6 on 2026-06-24 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_tabelaserie_periodicidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaserie',
            name='percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Percentual (%)'),
        ),
    ]
