# Generated by Django 6.0.5 on 2026-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='empresa',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.empresa', verbose_name='Empresas'),
        ),
    ]
