# Generated by Django 6.0.6 on 2026-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_deletado_em_empresa_deletado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='inc_empresa',
        ),
        migrations.AlterModelTable(
            name='historicalempresa',
            table='inc_historical_empresa',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='inc_userprofile',
        ),
    ]
