# Generated by Django 6.0.6 on 2026-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalpessoa',
            table='inc_historical_pessoa',
        ),
        migrations.AlterModelTable(
            name='historicaltipopapel',
            table='inc_historical_tipo_papel',
        ),
        migrations.AlterModelTable(
            name='pessoa',
            table='inc_pessoa',
        ),
        migrations.AlterModelTable(
            name='pessoapapel',
            table='inc_pessoa_papel',
        ),
        migrations.AlterModelTable(
            name='tipopapel',
            table='inc_tipo_papel',
        ),
    ]
