# Generated by Django 6.0.6 on 2026-06-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_historicalpessoa_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpessoa',
            name='conjuge',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.pessoa', verbose_name='Cônjuge'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='conjuge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuge_de', to='pessoas.pessoa', verbose_name='Cônjuge'),
        ),
    ]
