# Generated by Django 6.0.6 on 2026-06-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_conjuge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, help_text='Ex: Sócio-Administrador, Procurador', max_length=100, verbose_name='Cargo')),
                ('pessoa_fisica', models.ForeignKey(limit_choices_to={'tipo': 'pf'}, on_delete=django.db.models.deletion.PROTECT, related_name='representa', to='pessoas.pessoa', verbose_name='Representante')),
                ('pessoa_juridica', models.ForeignKey(limit_choices_to={'tipo': 'pj'}, on_delete=django.db.models.deletion.CASCADE, related_name='representantes_legais', to='pessoas.pessoa', verbose_name='Pessoa Jurídica')),
            ],
            options={
                'verbose_name': 'Representante Legal',
                'verbose_name_plural': 'Representantes Legais',
                'db_table': 'inc_representante_legal',
                'unique_together': {('pessoa_juridica', 'pessoa_fisica')},
            },
        ),
    ]
